/* ============ Hungarian layer, natural, idiomatic business Hungarian ============
   Keyed by the English source string. t() falls back to EN if a key is missing.
   Tone: warm, personal "te". Uses "AI" and "lead" (hot/warm/cold) as in real HU business speak. */
window.HU = {
  // ---- Problems ----
  "You answer the same questions every day": "Minden nap ugyanazt magyarázod el újra",
  "The same advice, the same intro, the same objections, typed out by hand, again. Your expertise is stuck on repeat.": "Ugyanaz a tanács, ugyanaz a bemutatkozás, ugyanazok a kifogások, megint kézzel begépelve. A szaktudásod ismétlésre van ítélve.",
  "Admin eats the hours clients pay for": "Az admin elviszi az órákat, amikért az ügyfél fizet",
  "DMs, email, scheduling, notes. The work that grows the business loses every time to the work that just keeps it alive.": "Üzenetek, e-mailek, időpontok, jegyzetek. Ami vinné előre a vállalkozást, mindig alulmarad azzal szemben, ami épp csak életben tartja.",
  "Warm leads go cold while you're busy": "A warm lead kihűl, amíg te máson dolgozol",
  "Nobody followed up at the right moment, so a buyer who was ready quietly went somewhere that answered faster.": "Senki nem jelentkezett a jó pillanatban, így a kész vevő csendben ahhoz ment, aki gyorsabban válaszolt.",
  "Every new client is a manual scramble": "Minden új ügyfél kézi kapkodással indul",
  "Forms, contracts, intro calls, assembled from scratch each time. Onboarding depends entirely on you remembering the steps.": "Űrlapok, szerződések, bemutatkozó hívások, mindig a nulláról. A beléptetés azon múlik, eszedbe jut-e minden lépés.",
  "Delivery quality swings with your energy": "A minőség az aktuális energiádtól függ",
  "Clients get the rested version of you or the exhausted one. Consistency shouldn't be a coin flip.": "Az ügyfél hol a kipihent, hol a kimerült éned kapja. A kiszámíthatóság ne szerencse kérdése legyen.",
  "You are the single point of failure": "Minden rajtad áll vagy bukik",
  "Nothing moves unless you move it. Growth doesn't buy you freedom, it just stacks more onto your plate.": "Semmi nem mozdul, ha te nem mozdítod. A növekedés nem szabadságot hoz, csak még többet pakol rád.",

  // ---- Quiz ----
  "Lead capture": "Lead-begyűjtés",
  "When a new enquiry comes in, does it get a personal reply within 5 minutes, automatically?": "Amikor új megkeresés jön, kap-e automatikusan személyes választ 5 percen belül?",
  "Follow-up": "Utánkövetés",
  "Do quiet leads get a sequenced follow-up without you having to remember to send it?": "Az elcsendesült leadek kapnak-e automatikus utánkövetést anélkül, hogy neked kellene rájuk emlékezned?",
  "Onboarding": "Beléptetés",
  "Do new clients get a personal onboarding flow without you assembling materials each time?": "Az új ügyfél végigmegy-e egy személyes beléptetési folyamaton anélkül, hogy minden alkalommal külön összerakd neki az anyagot?",
  "Reporting": "Riportok",
  "Can you see revenue, pipeline and key numbers live, without building a spreadsheet?": "Látod-e élőben a bevételt, a pipeline-t és a fő számokat anélkül, hogy táblázatot kellene építened?",

  // ---- Stats ----
  "of organisations now use AI in at least one business function.": "— a cégek ekkora hányadánál működik már AI legalább egy üzleti területen.",
  "of knowledge workers already use AI in their daily work.": "— a szellemi munkát végzők ekkora hányada használ AI-t a napi munkájában.",
  "average productivity gain from AI, measured in real workflows.": "— átlagos hatékonyság-növekedés AI-jal, valós munkafolyamatokban mérve.",

  // ---- Before / After ----
  "Drowning in DMs and email": "Fuldokolsz az üzenetekben és e-mailekben",
  "Onboarding every client by hand": "Minden ügyfelet kézzel léptetsz be",
  "Repeating the same answers on loop": "Ugyanazokat a válaszokat darálod",
  "Delivery that depends on you for everything": "A munka mindenben rajtad áll",
  "Leads going cold in your inbox": "A leadek a postafiókodban hűlnek ki",
  "Enquiries qualified and answered automatically": "A megkeresések maguktól minősülnek és kapnak választ",
  "A smooth, automated onboarding flow": "Gördülékeny, automata beléptetés",
  "Your expertise answering on autopilot": "A szaktudásod válaszol helyetted, automatán",
  "A premium, consistent client experience": "Prémium, egyenletes ügyfélélmény",
  "A business that runs without you in every step": "Egy vállalkozás, ami nem rajtad múlik minden lépésnél",

  // ---- Fit ----
  "You're a coach, consultant or expert advisor with real, paying demand.": "Coach, tanácsadó vagy szakértő vagy, valódi, fizető kereslettel.",
  "You're losing 10+ hours a week to manual operations.": "Heti 10+ órád megy el kézi munkára.",
  "You want a done-for-you system, not another course to grind through.": "Kulcsrakész rendszert szeretnél, nem egy újabb kurzust, amit végig kell rágni.",
  "You're ready to invest in operations that compound over time.": "Készen állsz olyan rendszerbe fektetni, ami idővel kamatozik.",
  "You're pre-revenue or still validating the idea.": "Még bevétel előtt vagy, vagy még teszteled az ötletet.",
  "You want to build and maintain everything yourself.": "Mindent magad akarsz megépíteni és karbantartani.",
  "You're hunting for the cheapest possible option.": "A legolcsóbb megoldást keresed.",
  "You need it \"done by tomorrow\" with no discovery.": "„Holnapra kész” kell, felmérés nélkül.",

  // ---- Services ----
  "AI Client Onboarding": "AI ügyfélbeléptetés",
  "Automate qualification, intake and onboarding so every new client starts smoothly, without your manual work.": "Automata minősítés, felvétel és beléptetés, hogy minden új ügyfél gördülékenyen induljon, kézi munka nélkül.",
  "AI Knowledge Assistant": "AI tudásasszisztens",
  "Train an AI on your own frameworks and methodology so your expertise answers clients around the clock.": "Egy AI a saját módszertanodra tanítva, hogy a szaktudásod éjjel-nappal válaszoljon az ügyfeleknek.",
  "AI Content Engine": "AI tartalommotor",
  "Turn your calls, notes and ideas into ready-to-post content automatically, so you stay visible without the grind.": "A hívásaidból, jegyzeteidből és ötleteidből magától kész tartalom, hogy látható maradj a gürcölés nélkül.",
  "AI Client Success System": "AI ügyfélsiker-rendszer",
  "Track clients, follow-ups and next actions so nothing slips and delivery stays consistently premium.": "Ügyfelek, utánkövetések és teendők egy helyen, hogy semmi ne csússzon ki, és a munka végig prémium maradjon.",
  "AI Sales Assistant": "AI értékesítési asszisztens",
  "Nurture and qualify leads 24/7 so your pipeline keeps moving while you focus on delivery.": "Leadek gondozása és minősítése a nap 24 órájában, hogy pörögjön a pipeline, amíg te a munkára figyelsz.",
  "AI Delivery Workflows": "AI munkafolyamatok",
  "Turn your repeatable processes and SOPs into systems that run themselves behind the scenes.": "Az ismétlődő folyamataidból a háttérben magától futó rendszer lesz.",

  // ---- Process ----
  "Audit": "Felmérés",
  "We start with a relaxed conversation. I get to know how you actually work, then map the bottlenecks and the exact gaps where your time and revenue quietly leak out.": "Egy kötetlen beszélgetéssel indulunk. Megnézem, hogyan dolgozol valójában, aztán feltérképezem, hol akad meg a folyamat, és pontosan hol szivárog el az időd és a bevételed.",
  "System Design": "Rendszertervezés",
  "Then I design a practical automation structure around how your business really works, never a generic template. You see exactly what I'm building and why.": "Aztán egy működő, gyakorlatias automatizálást tervezek a te valódi működésedre szabva, sosem sablonból. Végig látod, mit építek és miért.",
  "Implementation": "Megvalósítás",
  "I build the workflows into your own accounts, walk you through everything, and keep refining with you until they genuinely run on their own.": "A folyamatokat a saját fiókjaidba építem, mindent megmutatok, és addig csiszoljuk együtt, amíg tényleg magától nem megy.",

  // ---- FAQ ----
  "Will this replace my personal brand?": "Lecseréli ez a személyes márkámat?",
  "No, it amplifies it. The systems run the repetitive operations in the background so you show up more, not less. Your voice, your frameworks and your client relationships stay entirely yours.": "Nem, felerősíti. A rendszerek a háttérben viszik az ismétlődő melót, így te többet tudsz jelen lenni, nem kevesebbet. A hangod, a módszered és az ügyfélkapcsolataid teljesen a tieid maradnak.",
  "Will it sound robotic or impersonal?": "Nem lesz robotos vagy személytelen?",
  "No. Everything is trained around your tone, your methodology and your workflows, so clients get a faster, more consistent version of you, not a generic bot.": "Nem. Minden a te stílusodra, módszeredre és folyamataidra épül, így az ügyfél egy gyorsabb, kiszámíthatóbb verziódat kapja, nem egy sablonos botot.",
  "Will it work with my current tools?": "Működik azzal, amit most használok?",
  "Yes. I build around the stack you already use, calendar, email, CRM, payments, instead of asking you to switch everything. Your setup stays familiar.": "Igen. Arra építek, amit már használsz — naptár, e-mail, CRM, fizetés —, nem kell mindent lecserélned. A megszokott rendszered marad.",
  "What does it cost?": "Mibe kerül?",
  "There's no fixed price list. Every system is scoped to your operation, its complexity and your goals. Most engagements combine a one-time build with optional ongoing operation. We agree the exact scope and investment together on the audit call, no obligation.": "Nincs fix árlista. Minden rendszer a te működésedre, annak bonyolultságára és a céljaidra van szabva. Általában egy egyszeri kiépítés és egy opcionális, havi üzemeltetés a felállás. A pontos tartalmat és az árat a felmérő beszélgetésen tisztázzuk, kötöttség nélkül.",
  "What if I'm not technical?": "Mi van, ha nem értek a technikához?",
  "That's the point. You don't need to be. I build and run the system; you just use it. I walk you through everything at handover, and the monthly partnership means you never maintain it yourself.": "Pont ez a lényeg, nem is kell értened. Én építem és üzemeltetem, te csak használod. Átadáskor mindent megmutatok, és a havi együttműködés miatt sosem neked kell karbantartani.",
  "How much of my time does it take?": "Mennyi időmet viszi el?",
  "Very little. We need 1-2 conversations to scope it (about 2 hours total) and a short handover session. I handle the build, and after handover the system runs in the background.": "Keveset. 1-2 beszélgetés kell a tervezéshez (összesen kb. 2 óra) és egy rövid átadás. Az építést én viszem, az átadás után a rendszer magától fut a háttérben.",
  "What if it doesn't work the way we planned?": "Mi van, ha nem úgy működik, ahogy terveztük?",
  "I fix it. I don't work on a \"closed invoice\" basis. I keep refining the system until it genuinely serves your business, which is exactly why we start with a no-pressure call to make sure we're a fit.": "Megoldom. Nálam nincs olyan, hogy „kiszámláztam, viszlát”. Addig csiszolom a rendszert, amíg tényleg a vállalkozásodat szolgálja, épp ezért kezdünk egy nyomásmentes beszélgetéssel, hogy lássuk, passzolunk-e.",
  "How is this different from an AI course or agency?": "Miben más ez, mint egy AI-kurzus vagy ügynökség?",
  "A course teaches you to build it yourself. An agency rents you their stack. I build a system into your own accounts, hand it over so it stays yours, and keep operating it with you. You get the outcome without becoming a tech team.": "Egy kurzus megtanít, hogy magad építsd. Egy ügynökség a saját rendszerét adja bérbe. Én a te fiókjaidba építem be a rendszert, átadom, hogy a tiéd legyen, és veled együtt üzemeltetem. Megkapod az eredményt anélkül, hogy techcsapattá kéne válnod.",

  // ---- Brands ----
  "English tuition for Hungarian professionals, structured fluency from beginner through C1. Enquiries, qualification, onboarding and follow-up all run automatically; I only get a ping when a new student joins.": "Angoltanítás magyar szakembereknek, felépített nyelvtudás kezdőtől C1-ig. A megkeresés, a minősítés, a beléptetés és az utánkövetés magától megy; nekem csak akkor jön jelzés, ha új diák lép be.",
  "Visit Entropy Breakers": "Tovább az Entropy Breakers oldalára",
  "Business communication and identity shift for DACH entrepreneurs. Same setup: leads captured and qualified automatically, onboarding on autopilot, day-to-day running in the background.": "Üzleti kommunikáció és énmárka DACH-vállalkozóknak. Ugyanaz a felállás: a leadek maguktól begyűlnek és minősülnek, a beléptetés robotpilótán, a napi működés a háttérben.",
  "Visit Get Client Ready": "Tovább a Get Client Ready oldalára",

  // ---- UI ----
  "Services": "Szolgáltatások",
  "How it works": "Hogyan működik",
  "Why QuietStack": "Miért QuietStack",
  "FAQ": "GYIK",
  "Book your free audit": "Kérd az ingyenes auditot",
  "Book your free systems audit": "Kérd az ingyenes rendszer-auditot",
  "See how it works": "Nézd meg, hogyan működik",
  "A personal reply from me within 24 hours": "Személyes válasz tőlem 24 órán belül",
  "EU-based · DSGVO-aligned": "EU-s · GDPR-konform",
  "Built into your own accounts": "A saját fiókjaidba építve",

  // ---- Hero ----
  "Replace yourself in your own business — with AI.": "Vedd ki magad a saját vállalkozásodból — AI-val.",
  "Your business shouldn't depend on you for every single step.": "A vállalkozásod ne minden egyes lépésnél múljon rajtad.",
  "Free audit": "Ingyenes audit",
  "Operational AI systems for coaches & consultants": "Operatív AI-rendszerek coachoknak és tanácsadóknak",
  "Operational AI systems": "Operatív AI-rendszerek",
  "Let your business run itself.": "Működjön a vállalkozásod magától.",
  "I build AI infrastructure that quietly runs your delivery and operations, so growth feels calmer, not heavier. You stay the expert. The busywork disappears.": "Olyan AI-rendszert építek, ami csendben elviszi helyetted a napi működést, így a növekedés nyugodtabb lesz, nem nehezebb. Te maradsz a szakértő, a robotmeló pedig eltűnik.",
  "Most consultants don't need more leads. They need systems that survive scale. QuietStack builds the AI infrastructure that runs delivery, onboarding and follow-up in the background.": "A legtöbb tanácsadónak nem több lead kell, hanem rendszer, ami bírja a növekedést. A QuietStack azt az AI-hátteret építi meg, ami a munkát, a beléptetést és az utánkövetést a háttérből viszi.",
  "I'm Bettina, and I build AI infrastructure that runs delivery and operations quietly in the background, so your business stops depending on you for every single move.": "Bettina vagyok. Olyan AI-rendszert építek, ami csendben, a háttérből viszi a munkát és a működést, hogy a vállalkozásod ne minden apró lépésnél rajtad múljon.",
  "Founder": "Alapító",
  "Systems that survive scale": "Rendszer, ami bírja a növekedést",
  "You don't need more leads first.": "Nem több leadre van szükséged először.",
  "You don't need": "Nem több leadre",
  "more leads first.": "van szükséged először.",
  "You need a system that can": "Hanem egy rendszerre,",
  "carry your success.": "ami elbírja a sikered.",
  "freed up once your systems run": "szabadul fel, amint megy a rendszer",
  "QuietStack · Automations": "QuietStack · Automatizálás",
  "Live": "Élő",
  "0 manual steps · running while you focus": "0 kézi lépés · fut, amíg te a lényegre figyelsz",
  "New enquiry captured": "Új megkeresés rögzítve",
  "Sarah K. · just now": "Sarah K. · épp most",
  "Qualified · warm lead": "Minősítve · warm lead",
  "auto-tagged": "automata címkézés",
  "Welcome sequence sent": "Üdvözlő sorozat kiment",
  "personalised": "személyre szabva",
  "Discovery call booked": "Hívás lefoglalva",
  "Thu · 14:00": "Csüt · 14:00",
  "Most clients free up": "A legtöbb ügyfél heti",
  "20–30 hours a week": "20–30 órát nyer vissza",
  ", with the first systems working in days, not months.": ", az első rendszerek pedig napok alatt élesednek, nem hónapok alatt.",

  // ---- Sound familiar / audit / stats (SA) ----
  "Builds into the stack you already run on": "Arra épül, amit már használsz",
  "Sound familiar?": "Ismerős?",
  "Your business grows. Your operations turn to chaos.": "A vállalkozásod nő. A működésed káoszba csúszik.",
  "You\u2019re not behind, and you\u2019re not doing it wrong. <strong>You\u2019re just running on willpower instead of systems</strong>, and willpower doesn\u2019t scale. I\u2019ve been exactly there.": "Nem vagy lemaradva, és nem csinálsz semmit rosszul. <strong>Csak akaraterőből nyomod, rendszer helyett</strong>, az akaraterő viszont nem skálázódik. Pontosan onnan jövök, ahol most te vagy.",
  "60-second self-audit": "60 másodperces önteszt",
  "Where is your client flow leaking?": "Hol szivárog az ügyfélfolyamatod?",
  "Four questions. One honest answer each. No email required.": "Négy kérdés, mindre egy őszinte válasz. E-mail nem kell.",
  "Yes": "Igen",
  "No": "Nem",
  "Estimated leak": "Becsült veszteség",
  "hrs / week": "óra / hét",
  "Answer all four to see your estimate.": "Válaszolj mind a négyre a becslésért.",
  "Rare. Your operations are already tighter than most. Let's pressure-test the edges.": "Ritka eset. A működésed már most szervezettebb, mint a legtöbbnél. Nézzük meg, hol lehet még finomítani.",
  "Every stage is leaking. This is exactly where a system pays for itself fastest.": "Mindegyik szakasz szivárog. Pont itt térül meg egy rendszer a leggyorsabban.",
  "Map this properly": "Nézzük meg alaposan",
  "By the numbers": "Számokban",
  "The market has already moved.": "A piac már lépett.",
  "AI isn't the future you're preparing for. It's the operating advantage your competitors are already running on.": "Az AI nem a jövő, amire készülsz. Hanem az az előny, amin a versenytársaid már most futnak.",
  "The teams putting these numbers to work aren't bigger than you. They're just systematised. ": "Akik ezeket a számokat kihasználják, nem nagyobbak nálad, csak rendszerben gondolkodnak. ",
  "That's the only gap.": "Ennyi a különbség.",
  "What that looks like for you": "Mit jelent ez neked",
  "hours / week": "óra / hét",
  "freed up once your systems run, the equivalent of a part-time hire's time back, every single week.": "szabadul fel, amint megy a rendszer, ennyivel kapsz vissza egy részmunkaidős kolléga idejét, minden héten.",
  "First systems live in days, not months.": "Az első rendszerek napok alatt élesek, nem hónapok alatt.",

  // ---- Before/After · Philosophy · About · Fit (SB) ----
  "The shift": "A váltás",
  "Quiet systems build scalable businesses.": "A csendes rendszerek skálázható vállalkozást építenek.",
  "The same practice, before and after the systems are in place. Same expertise, wildly different leverage.": "Ugyanaz a vállalkozás, a rendszerek előtt és után. Ugyanaz a tudás, egészen más szabadság.",
  "Before": "Előtte",
  "After": "Utána",
  "How I see it": "Ahogy én látom",
  "Growth should create leverage, not operational chaos.": "A növekedés adjon szabadságot, ne működési káoszt.",
  "I've watched too many good businesses scale revenue faster than they scale systems. The result is hidden friction, inconsistent delivery, and a founder who can't step away without everything stalling. It doesn't have to be that way.": "Túl sok jó vállalkozást láttam, ami gyorsabban növelte a bevételt, mint a rendszereit. Az eredmény: rejtett súrlódás, ingadozó minőség, és egy alapító, aki nem tud kilépni, mert akkor minden leáll. Pedig nem kell ennek így lennie.",
  "So I design operational infrastructure that scales ": "Ezért olyan működési rendszert tervezek, ami ",
  "calmly": "nyugodtan",
  ", quiet in the background, structured by default, built to remove noise rather than pile on more tools.": " skálázódik, csendben a háttérben, alapból átláthatóan, hogy zajt vegyen le rólad, ne újabb eszközöket pakoljon rád.",
  "Founder, QuietStack": "Alapító, QuietStack",
  "About": "Rólam",
  "I quietly took myself out of my own business.": "Csendben kivettem magam a saját vállalkozásomból.",
  "For seven years I taught English to Hungarian professionals through Entropy Breakers. I was the curriculum, the scheduling, the support, the marketing, running on willpower, not systems.": "Hét éven át tanítottam angolt magyar szakembereknek az Entropy Breakers alatt. Én voltam a tananyag, az időpontfoglalás, a support, a marketing, akaraterőből, nem rendszerből.",
  "So I started building. Platforms, AI-assisted feedback loops, automated onboarding and follow-up. Quietly, the business stopped needing me everywhere. The work was never really about teaching language. It was about operations.": "Így nekiálltam építeni. Platformok, AI-támogatott visszajelzés, automata beléptetés és utánkövetés. Csendben a vállalkozásnak már nem kellettem mindenhol. Sosem a nyelvtanításról szólt igazán, hanem a működésről.",
  "That's the work I do now through QuietStack. ": "Ezt csinálom most a QuietStackkel. ",
  "If you're building something and you're already tired, you're in the right place.": "Ha építesz valamit, és már elfáradtál, jó helyen jársz.",
  "My own client base grew by two-thirds": "A saját ügyfélköröm kétharmaddal nőtt",
  " after I automated the operations of my business, while spending ": ", miután automatizáltam a vállalkozásom működését, közben ",
  "less time on admin, not more": "kevesebbet adminoztam, nem többet",
  ". More revenue, fewer manual hours. That's the whole point.": ". Több bevétel, kevesebb kézi óra. Pontosan erről szól az egész.",
  "How I help": "Miben segítek",
  "Custom AI infrastructure for client operations, delivery, onboarding, follow-up.": "Egyedi AI-rendszer az ügyfélfolyamatokra: munka, beléptetés, utánkövetés.",
  "Workflow automation that quietly removes friction.": "Folyamat-automatizálás, ami csendben leveszi a súrlódást.",
  "Systems audits for businesses ready to stop running on willpower.": "Rendszer-felmérés azoknak, akik már nem akarnak akaraterőből pörögni.",
  "Honest fit": "Őszinte illeszkedés",
  "Built for businesses ready to scale, not to start.": "Azoknak, akik már skáláznának, nem most kezdik.",
  "Fit matters more than a signed invoice. If this isn't you yet, I'll tell you straight.": "Fontosabb, hogy passzoljunk, mint egy aláírt számla. Ha ez még nem te vagy, megmondom őszintén.",
  "Perfect fit": "Tökéletes passz",
  "Probably not yet": "Valószínűleg még nem",

  // ---- Services · Process · Sovereignty · Guarantee · FAQ heads (SC) ----
  "What I build": "Amit építek",
  "Your expertise, running as a system.": "A szaktudásod, rendszerként.",
  "Concrete AI systems built around how you already work, so delivery scales without you in every step.": "Konkrét AI-rendszerek a meglévő működésedre szabva, hogy a munka skálázódjon anélkül, hogy minden lépésnél te kellenél.",
  "Simple systems. Clear implementation.": "Egyszerű rendszer. Tiszta megvalósítás.",
  "Three steps from operational bottlenecks to workflows that run themselves.": "Három lépés a megakadt folyamatoktól az önjáró rendszerig.",
  "Safe by design": "Eleve biztonságos",
  "Your accounts. Your data. Your IP.": "A te fiókjaid. A te adataid. A te tudásod.",
  "Built for businesses that take data seriously. The system lives inside the tools you already run, and stays entirely under your control.": "Azoknak, akik komolyan veszik az adatot. A rendszer a már használt eszközeidben él, és végig a te kezedben marad.",
  "Your accounts": "A te fiókjaid",
  "Systems are built directly into the tools you already own, calendar, email, CRM, payments. No new platform to migrate to, nothing to rip out.": "A rendszer közvetlenül a meglévő eszközeidbe épül, naptár, e-mail, CRM, fizetés. Nincs új platform, nincs költözés, nincs mit kidobni.",
  "Your data": "A te adataid",
  "Nothing leaves your stack. I don't pool, train on, or resell your data. EU-based and DSGVO-aligned by design, not as an afterthought.": "Semmi nem hagyja el a rendszeredet. Nem gyűjtöm, nem tanítok rajta, nem adom tovább az adataidat. EU-alapú és GDPR-konform, alapból, nem utólag.",
  "Your IP": "A te tudásod",
  "Your frameworks, content and client relationships stay 100% yours. At handover the system runs in your name, in your accounts.": "A módszered, a tartalmad és az ügyfélkapcsolataid 100%-ban a tieid maradnak. Átadáskor a rendszer a te neveden, a te fiókjaidban fut.",
  "Why it's safe to start": "Miért biztonságos belevágni",
  "Clear scope, agreed up front, so it's safe for both of us.": "Tiszta keretek, előre lefektetve, hogy mindkettőnknek biztonságos legyen.",
  "My promise to you": "Az én ígéretem",
  "You'll always know where things stand.": "Mindig tudni fogod, hol tartunk.",
  "Before we build, we shape together what a finished, working system looks like for you, the outcomes that matter and what \"done\" really means. So there's no guesswork, and no quiet drift, just a clear shared picture from the very first day.": "Mielőtt építünk, közösen letisztázzuk, milyen neked a kész, működő rendszer: mik a fontos eredmények, és mit jelent pontosan a „kész”. Így nincs találgatás és nincs csendes elcsúszás, tiszta, közös kép az első naptól.",
  "And after handover, there's a dedicated window to fine-tune everything until it feels right in your hands. Calm, considered and fair to us both, the way good work should feel.": "Átadás után pedig van egy külön szakasz, amíg mindent finomhangolunk, hogy a kezedben is jól álljon. Nyugodtan, átgondoltan, mindkettőnkhöz fair módon, ahogy a jó munkának lennie kell.",
  "Founding clients": "Alapító ügyfelek",
  "Intentionally small. Limited spots.": "Szándékosan kicsi. Korlátozott hely.",
  "QuietStack is new and stays small on purpose. I take on a limited number of founding clients at a time, at a reduced build fee.": "A QuietStack új, és szándékosan kicsi marad. Egyszerre csak pár alapító ügyfelet veszek fel, kedvezményes építési díjjal.",
  "In return, we document a detailed case study together, and founding clients keep their rate for good. When the spots are full, they're full.": "Cserébe közösen csinálunk egy részletes esettanulmányt, és az alapító ügyfelek tartósan tartják az árukat. Ha betelik a hely, betelik.",
  "The questions most people ask first.": "Amit a legtöbben először kérdeznek.",

  // ---- Final CTA · Brands · Footer (SD) ----
  "Your move": "Te jössz",
  "Free and no obligation. You leave with a clear roadmap, yours to keep, whether we work together or not.": "Ingyenes és kötöttség nélküli. Egy tiszta tervvel távozol, ami a tiéd marad, akár dolgozunk együtt, akár nem.",
  "AI isn't coming. It's already running your competitors' back office.": "Az AI nem jön. Már most a versenytársaid hátterét pörgeti.",
  "The few who systematise will pull away quietly, while everyone else stays busy. I'd love to help you be one of them. Let's have a relaxed chat and see if we're a fit, no pressure either way.": "Aki rendszerez, csendben elhúz, a többiek meg maradnak az örök pörgésben. Szívesen segítek, hogy te az előbbi légy. Beszélgessünk egy nyugodtat, és nézzük meg, passzolunk-e. Nyomás nincs.",
  "Also building": "Ezeket is én viszem",
  "Two other brands I run on the same systems.": "Két másik márkám, ugyanezeken a rendszereken.",
  "Quiet systems. Scalable operations. AI-assisted operational infrastructure for coaches and high-ticket consultants.": "Csendes rendszerek. Skálázható működés. AI-támogatott operatív háttér coachoknak és magas árszintű tanácsadóknak.",
  "Explore": "Felfedezés",
  "Get started": "Vágj bele",
  "Contact": "Kapcsolat",
  "Self-audit": "Önteszt",
  "Book an audit": "Felmérés foglalása",
  "Email": "E-mail",
  "A service by Entropy Breakers": "Az Entropy Breakers szolgáltatása",
  "Based in Austria · online, wherever you are": "Ausztriából · online, bárhol is vagy",
  "Imprint · Privacy Policy · Terms & Conditions": "Impresszum · Adatvédelem · ÁSZF",
  "Imprint": "Impresszum",
  "Privacy Policy": "Adatvédelem",
  "Terms & Conditions": "ÁSZF",
};
